### ISSUE TITLE
Imitate RuneLite GUI

### ISSUE THREAD

**Issue by GigiaJ** [OSRSB/OsrsBot#5]
At a later time, it'd be even more optimal to emulate RuneLite's gui to look even less suspicious.

**Comment by f0rmatme** [comment]
OpenOSRS will support tornadofx soon which might be better to use. 
https://prnt.sc/rucnjz

**Comment by GigiaJ** [comment]
I was actually planning on updating the GUI to act as a plugin, for easier integration. Obviously it'll have more functionality than your normal RuneLite plugin, but it'll allow much, much smoother interaction between the two APIs.

**Comment by GigiaJ** [comment]
#49 is the beginning of creating this functionality. (Haven't removed legacy gui code and such, but moving away from using much of it)
