### ISSUE TITLE
[BUG] Clan Chat Tab may be broken

### ISSUE THREAD

**Issue by GigiaJ** [OSRSB/OsrsBot#65]
**BEFORE REPORTING**
Ensure RuneLite is up to date in IDE and you are using the latest version of the master branch

**Describe the bug**
It appears as if RuneLite (and likely OSRS) has removed the clan chat tab and other in-game occurrences of clan stuff. So it is very likely the API won't compile currently as we use references to the RuneLite usages. 

**Expected behavior**
The API compiles and executes properly. All references that are invalid need to be removed.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by slymerchant** [comment]
change ClanChatManager to FriendChatManager and all references to FriendChat
